name: stoke_scanner
description: Demonstrates how to use the flutter_qr plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  sqflite_common_ffi: ^2.3.0+2
  path_provider: ^2.1.0
  path: ^1.8.3
  sqflite: ^2.3.0
  card_swiper : ^3.0.0
  animated_icon_button: ^1.0.2
  text_form_field_wrapper: ^1.0.0
  phone_form_field: ^8.1.0
  flutter_exit_app: ^1.1.2
  animated_splash_screen: ^1.3.0
  scroll_loop_auto_scroll: ^0.0.5
  scroll_snap_list: ^0.9.1
  cupertino_icons: ^1.0.2
  ticket_widget: ^0.0.1
  http: ^1.1.0
  persistent_bottom_nav_bar: ^4.0.0
  flutter_progress_hud: ^2.0.2
  column_scroll_view: ^1.0.4
  qr_flutter: ^4.0.0 
  flutter_zoom_drawer: ^3.1.1
dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Preahvihear-Regular
     fonts:
        - asset: fonts/Preahvihear-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
